version: '3.6'

services:
  web:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: sylius-web
    volumes:
      - ${NGINX_CONF_DIR_VHOST:-./.docker/nginx}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR:-./.docker/nginx/logs}:/var/log/nginx
      - ./${PROJECT_WEB}:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - mysql
    networks:
      - sylius-ntwk

  sylius:
    container_name: sylius-sylius
    build:
      dockerfile: ./.docker/sylius/Dockerfile
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - APP_DEBUG=${APP_DEBUG:-1}
      - PHP_VERSION=${PHP_VERSION}
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
    volumes: 
      - ./${PROJECT_WEB}:/var/www/html/
      - ./.docker/sylius/php/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
      - ./.docker/sylius/php/php-cli.ini:/usr/local/etc/php/conf.d/php-cli-custom.ini
    ports:
      - "9900:8000"
      - "9901:8001"
    # command: sh -c "chown -R www-data:www-data /var/www/html/"
    networks:
      - sylius-ntwk

  mysql:
    container_name: sylius-db
    image: mariadb:10.4
    restart: always
    ports:
      - 33306:3306
    volumes:
        - .docker/mysql/data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-thepassword}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-sylius_db}"
      - "MYSQL_USER=${MYSQL_USER:-sylius_du}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-thesecret}"
    networks:
      - sylius-ntwk

  mailhog:
    container_name: ddr_mailhog
    image: 'mailhog/mailhog:latest'
    ports:
        - '${FORWARD_MAILHOG_PORT:-1025}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sylius-ntwk

  adminer:
    container_name: sylius-adminer
    image: adminer
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - mysql
    networks:
      - sylius-ntwk

networks:
  sylius-ntwk: